import logging
from datetime import date

from flask import Blueprint, jsonify, request

from ingest.auth import require_secret
from ingest.db import connection
from ingest.parsers import baselines_idealista

logger = logging.getLogger("ingest.routes_baselines")

bp = Blueprint("baselines", __name__)


@bp.route("/ingest/baselines", methods=["POST"])
@require_secret
def ingest_baselines():
    body = request.get_json(silent=True) or {}
    url = body.get("url")
    html = body.get("html")
    if not url or not html:
        return jsonify({"error": "url and html are required"}), 400

    try:
        price_per_sqm = baselines_idealista.parse_baselines(url, html)
    except Exception as exc:  # noqa: BLE001 -- a malformed/unexpected page
        # must come back as a clean 400, never a raw 500 traceback (this
        # endpoint has no capture_queue row to retry against, unlike
        # routes_detail's _fail(), so there's nothing to escalate -- just
        # report the bad input).
        logger.exception("Unhandled error parsing baselines page %s", url)
        return jsonify({"error": str(exc)}), 400

    if price_per_sqm is None:
        return jsonify({"error": "parse failed"}), 400

    # NAIVE URL-TO-AREA-SLUG MATCH -- UNVERIFIED against real Idealista
    # URLs (see task-4-report.md). This assumes Idealista's own URL slug
    # for a location matches this project's areas.slug column exactly.
    # areas.slug is generated by web/prisma/seed.ts's slugify() (NFD-
    # normalize, strip diacritics, lowercase, non-alphanumeric runs -> '-')
    # applied to Portuguese freguesia names in config.json, e.g. "Sao
    # Domingos de Rana" -> "sao-domingos-de-rana". Nobody has confirmed
    # what Idealista's real price-report URLs look like -- freguesia-level
    # or municipality-level, same diacritic handling or not -- so this
    # match cannot be fully verified either. It IS safe to leave naive,
    # though: if the slug doesn't match any area, the SELECT below returns
    # no row, we respond 404, and nothing is written -- there is no
    # fallback path that writes against the wrong area or fabricates one.
    slug = url.rstrip("/").split("/")[-1]

    try:
        with connection() as conn:
            row = conn.execute(
                "SELECT id FROM areas WHERE slug = %s", (slug,)
            ).fetchone()
            if not row:
                return jsonify({"error": "area not found"}), 404

            conn.execute(
                """
                INSERT INTO area_price_baselines
                (id, area_id, source, metric_type, period, price_per_sqm,
                 captured_at, created_at, updated_at)
                VALUES (gen_random_uuid()::text, %s, 'idealista', 'asking',
                        %s, %s, now(), now(), now())
                ON CONFLICT (area_id, source, metric_type, period)
                DO UPDATE SET price_per_sqm = EXCLUDED.price_per_sqm,
                              captured_at = now(), updated_at = now()
                """,
                (row["id"], date.today().replace(day=1), price_per_sqm),
            )
            conn.commit()
    except Exception as exc:  # noqa: BLE001 -- DB errors must also come
        # back as a clean 400 rather than an unhandled 500, matching how
        # routes_detail.py / routes_queue.py never let a raw traceback
        # reach the caller.
        logger.exception("Unhandled error writing baseline for %s", url)
        return jsonify({"error": str(exc)}), 400

    return jsonify({"status": "success", "price_per_sqm": str(price_per_sqm)})
